- name: faceshift
  class: Faceshift
  enabled: false
  sourcetopic: faceshift_track
  binding:
    meshname: Head
    singles: []
      #- varpath: m_headRotation:x
      #  bonerot: Armature:bracket3:x
      #- varpath: m_headRotation:y
      #  bonerot: Armature:base:y
      #- varpath: m_headRotation:z
      #  bonerot: Armature:bracket2:z

- name: chest_pivision
  class: NRegionsOfInterest
  enabled: true
  rosbind:
    #namespace: chest
    eventtopic: tracking_event
    sourcetopic: faces/%d
  blenderbind:
    objectpos:
      # coordinates of the center of the webcam screen in blender space.
      offset: [0.008,-1,0.458737]
      scale: 1.5

- name: eye_pivision
  class: NRegionsOfInterest
  enabled: true
  rosbind:
    namespace: eye
    eventtopic: tracking_event
    sourcetopic: faces/%d
  blenderbind:
    objectpos:
      offset: RightEye
      direction: eyefocus
      distance: 1
      scale: 1
