- name: neck_euler
  class: ParametersOut
  enabled: true
  pubtopic: point_head
  msg: basic_head_api.msg.PointHead
  binding:
    - varpath: yaw
      bonerot: Armature:base:y
    - varpath: pitch
      bonerot: Armature:bracket3:x
    - varpath: roll
      bonerot: Armature:bracket2:z

- name: face
  class: ParametersOut
  enabled: true
  pubtopic: cmd_face_pau
  msg: pau2motors.msg.pau
  binding:
    - varpath: m_coeffs
      shkey_mesh: Head

- name: eyes
  class: ParametersOut
  enabled: true
  pubtopic: cmd_eyes_pau
  msg: pau2motors.msg.pau
  binding:
    - varpath: m_eyeGazeLeftPitch
      bonerot: leye:leyebone:x
    - varpath: m_eyeGazeLeftYaw
      bonerot: leye:leyebone:z
    - varpath: m_eyeGazeRightPitch
      bonerot: reye:reyebone:x
    - varpath: m_eyeGazeRightYaw
      bonerot: reye:reyebone:z

- name: full_head
  class: CompositeOut
  enabled: true
  outputs:
    - neck_euler
    - face
    - eyes